<?xml version="1.0"?>
<package format="3">
  <name>db_logger</name>
  <version>0.0.1</version>
  <description>ROS2 node that subscribes to /status and /voice_command and writes to MySQL DB</description>
  <maintainer email="domcove9@gmail.com">ahn</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
